language: ruby
rvm:
  - 2.3.1
notifications:
  email: false

branches:
  except:
    - production

addons:
  postgresql: "9.3"

services:
  - redis-server

bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler

before_script:
  - psql -c 'create database ans_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
  - cp config/private_pub.travis.yml config/private_pub.yml
  - bundle exec rake db:setup
  - 'bundle exec rackup -s thin -E production private_pub.ru &'
  - sleep 5

script:
  - SKIP_BG=1 bundle exec rspec --tag ~visual --tag ~sphinx

gemfile:
  - Gemfile

